default_install_hook_types: [commit-msg, pre-commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
        exclude: 3rd_party
      - id: end-of-file-fixer

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.6
    hooks:
      - id: sqlfluff-fix
        stages: [pre-commit]
        args: ["--dialect", "postgres"]

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.6
    hooks:
      - id: sqlfluff-lint
        stages: [pre-commit]
        args: ["--dialect", "postgres"]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
