version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5439:5432"
    networks:
      - pg_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sql_applier:
    build: .
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: admin
      DB_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - pg_network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    networks:
      - pg_network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  pg_network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
